# Generated by Django 4.1.6 on 2023-02-06 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviebbs', '0002_rename_category_name_article_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
