# Generated by Django 4.1.6 on 2023-02-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviebbs', '0003_remove_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='movie_url',
            field=models.URLField(max_length=255),
        ),
    ]
