# Generated by Django 4.1.6 on 2023-02-13 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviebbs', '0006_remove_article_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='discription',
            new_name='text',
        ),
    ]
