# Generated by Django 4.1.6 on 2023-02-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviebbs', '0007_rename_discription_article_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='movie_id',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
