# Generated by Django 4.1.6 on 2023-02-14 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviebbs', '0009_article_last_commented_at_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='last_commented_at',
        ),
    ]
