# Generated by Django 4.1.7 on 2023-04-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviebbs', '0014_parentcategory_alter_article_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='カテゴリ名'),
        ),
        migrations.AlterField(
            model_name='parentcategory',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='親カテゴリ名'),
        ),
    ]
