# Generated by Django 4.1.7 on 2023-04-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviebbs', '0015_alter_category_name_alter_parentcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='movie_platform',
            field=models.CharField(default='youtube', max_length=50),
        ),
    ]
